CREATE TABLE topics (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
	id SERIAL PRIMARY KEY,
	topic_id INTEGER REFERENCES topics(id) ON UPDATE CASCADE ON DELETE CASCADE,
	contents TEXT NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
